[package]
name = "Project"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.228"
octocrab = "0.47.0"
tokio = { version = "1.48.0", features = ["full"] }
anyhow = "1.0.100"
clap = "4.5.50"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "tls-native-tls"] }
